# FROM jenkins/jenkins
# USER root
# WORKDIR /var/jenkins_home/
# RUN apt-get update && apt-get install -y lsb-release
# RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
#   https://download.docker.com/linux/debian/gpg
# RUN echo "deb [arch=$(dpkg --print-architecture) \
#   signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#   https://download.docker.com/linux/debian \ 
#   $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
# RUN apt-get update && apt-get install -y docker-ce-cli
#COPY
#ADD 
#ENV
#LABEL 
# VOLUME /var/run/docker.sock /var/run/docker.sock
# EXPOSE 8080/tcp 443/tcp 
#ENTRYPOINT [""]
#CMD [""]